config = {
    'name': 'en_de_translation',
    'embed_dim': 512,
    'n_blocks': 3,
    'n_heads': 8,
    'mlp_expansion_dim': 256,
    'dropout': 0.1,
    'max_length': 100,
    'device': 'cuda',
    'lr': 0.0005,
    'log_dir': 'logs',
    'weights_dir': 'weights',
    'save_interval': 1,
    'base_url': 'https://raw.githubusercontent.com/multi30k/dataset/master/data/task1/raw/',
    'train_urls': ('train.de.gz', 'train.en.gz'),
    'val_urls': ('val.de.gz', 'val.en.gz'),
    'test_urls': ('test_2016_flickr.de.gz', 'test_2016_flickr.en.gz'),
    'train_batch_size': 16,
    'val_batch_size': 16,
    'epochs': 20
}
